module.exports = {
    INIT: 'Init',
    REVIEW: 'Review',
    VOTING: 'Voting',
    QUEST_TEAMING: 'Teaming',
    QUEST_REVIEW: 'QuestReview',
    QUEST_GOING: 'QuestGoing',
    ASSASSIN: 'Assassinating',
    END_GOOD: 'GoodEnd',
    END_EVIL: 'EvilEnd',
    READY: 'Ready',
    NOT_READY: 'Not Ready',
    LEADER: 'Leader',
    WAITING: 'Waiting',
    LADY_GIVE: 'Giving lady',
    LADY_INVESTIGATING: 'Investigating',
    LADY_INVESTIGATED: 'Investigated',
    LADY_REVIEW: 'LadyReview',
};
